title: 'BitDevs Torino'
tagline: 'BitDevs Torino is a monthly meetup and developer-community for students, developers, and researchers in Turin who are interested in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Events', url: '/events'}
  - {name: 'Blog', url: '/blog'}
  - {name: 'Meetup', url: 'https://www.meetup.com/bitdevs-torino/', external: true}
  - {name: 'Cities', url: '/cities'}
